name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout source
      uses: actions/checkout@v3
    -
      name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.16
    -
      name: Install cookie
      run: scripts/gogetcookie.sh
    -
      name: Run tests
      env:
        GOFLAGS: "-mod=vendor"
      run: |
        make test
        make vet
